//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectInfo
    {
        public int id { get; set; }
        public string PName { get; set; }
        public string PCity { get; set; }
        public string MchineNum { get; set; }
        public string Salesman { get; set; }
        public string StartTime { get; set; }
        public string SalesPhone { get; set; }
        public string SubmitTime { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public Nullable<int> IsNow { get; set; }
    }
}
