//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectInfo
    {
        public int id { get; set; }
        public string pname { get; set; }
        public string pjCity { get; set; }
        public string machineNum { get; set; }
        public Nullable<int> isNow { get; set; }
        public string pjXSName { get; set; }
        public Nullable<int> isDealer { get; set; }
        public string phone { get; set; }
        public string other { get; set; }
    }
}
